# Generated by Django 5.1.7 on 2025-04-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acessorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acessorio',
            name='decricao',
        ),
        migrations.AddField(
            model_name='acessorio',
            name='descricao',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
