# Generated by Django 5.1.7 on 2025-04-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_acessorio_decricao_acessorio_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorio',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
